name: AfterGlowLuxuryAirbrushTanning
favicon: null
layout_spectrum: 0.75274
typography_spectrum: 1
title: AfterGlow Luxury Airbrush Tanning
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ef1e71'
    - '#3ba8bd'
    - '#363435'
    - '#7ebd3b'
    - '#dc0a63'
  brandStrength: 0.125
  lightness: 0.5412653917446733
  saturation: 0.5777319720946252
  rhythmicContrast: 0.9796149891335517
purpose: []
