name: AfterGlowLuxuryAirbrushTanning
favicon: null
layout_spectrum: 0.8534565803129226
typography_spectrum: 0.3635662232991308
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.49507892061956227
  lightness: 0.5412653917446733
  saturation: 0.5777319720946252
  rhythmicContrast: 0.9796149891335517
purpose: []
