name: AfterGlowLuxuryAirbrushTanning
favicon: null
layout_spectrum: 0.56303
typography_spectrum: 0.3635662232991308
title: AfterGlow Luxury Airbrush Tanning
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fb01ff'
    - '#25fefe'
    - '#fd8cff'
    - '#b0501d'
  brandStrength: 0.5625
  lightness: 0.5412653917446733
  saturation: 0.5777319720946252
  rhythmicContrast: 0.9796149891335517
purpose: []
